BASE_SLIDE_MAG = 400

INFERENCE_INPUT_MAG = 100
INFERENCE_INPUT_SIZE = 1024
INFERENCE_INPUT_STRIDE = 512

INFERENCE_OUTPUT_SIZE = 256

TARGET_SLIDE_MAG = 200
TARGET_RESIZE_RATIO = int((TARGET_SLIDE_MAG / INFERENCE_INPUT_MAG) * (INFERENCE_INPUT_SIZE / INFERENCE_OUTPUT_SIZE)) # 16

THRESHOLD = 0.5
